export const recipeData = [
  {
    id: 1,
    name: "Chicken Parmesan",
    img: "/chicken-parm.jpg",
    user: {
      name: "Chris"
    },
    information: {
      servings: 4,
      prepTime: 15,
      cookTime: 20,
      totalTime: 45,
      nuritionPerServing: {
        calories: 471,
        fat: 25,
        carbs: 25,
        protein: 42,
      },
      ingredients: [
        "4 skinless, boneless chicken breast halves",
        "salt and freshly ground black pepper to taste",
        "2 large eggs",
        "1 cup panko bread crumbs",
        "¾ cup grated Parmesan cheese, divided",
        "2 tablespoons all-purpose flour",
        "½ cup olive oil for frying",
        "½ cup prepared tomato sauce",
        "¼ cup fresh mozzarella, cut into small cubes",
        "¼ cup chopped fresh basil",
        "½ cup grated provolone cheese",
        "2 teaspoons olive oil",
      ],
      steps: [
        "Preheat an oven to 450 degrees F (230 degrees C).",
        "Place chicken breasts between two sheets of heavy plastic (resealable freezer bags work well) on a solid, level surface. Firmly pound chicken with the smooth side of a meat mallet to a thickness of 1/2-inch.",
        "Season chicken thoroughly with salt and pepper. Using a sifter or strainer; sprinkle flour over chicken breasts, evenly coating both sides",
        "Beat eggs in a shallow bowl and set aside.",
        "Mix bread crumbs and 1/2 cup Parmesan cheese in a separate bowl, set aside.",
        "Dip a flour-coated chicken breast in beaten eggs. Transfer breast to the bread crumb mixture, pressing crumbs into both sides. Repeat for each breast. Let chicken rest for 10 to 15 minutes.",
        "Heat 1/2 inch olive oil in a large skillet on medium-high heat until it begins to shimmer. Cook chicken in the hot oil until golden, about 2 minutes per side. The chicken will finish cooking in the oven.",
        "Transfer chicken to a baking dish. Top each breast with 2 tablespoons tomato sauce. Layer each chicken breast with equal amounts of mozzarella cheese, fresh basil, and provolone cheese. Sprinkle remaining Parmesan over top and drizzle each with 1/2 teaspoon olive oil.",
        "Bake in the preheated oven until cheese is browned and bubbly and chicken breasts are no longer pink in the center, 15 to 20 minutes. An instant-read thermometer inserted into the center should read at least 165 degrees F (74 degrees C).",
      ],
    },
    reviews: [
      {
        user: "Bob",
        rating: 4,
        comment: "Nice!",
      },
      {
        user: "Jim",
        rating: 3,
        comment: "Cool!",
      },
      {
        user: "Nate",
        rating: 4.5,
        comment: "Sick!",
      },
    ],
    created: "August 29, 2023",
  },
  {
    id: 2,
    name: "Penne Alla Vodka",
    img: "/penne-alla-vodka.jpg",
    user: {
      name: "Chris"
    },
    information: {
      servings: 4,
      prepTime: 15,
      cookTime: 20,
      totalTime: 45,
      nuritionPerServing: {
        calories: 471,
        fat: 25,
        carbs: 25,
        protein: 42,
      },
      ingredients: [
        "4 skinless, boneless chicken breast halves",
        "salt and freshly ground black pepper to taste",
        "2 large eggs",
        "1 cup panko bread crumbs",
        "¾ cup grated Parmesan cheese, divided",
        "2 tablespoons all-purpose flour",
        "½ cup olive oil for frying",
        "½ cup prepared tomato sauce",
        "¼ cup fresh mozzarella, cut into small cubes",
        "¼ cup chopped fresh basil",
        "½ cup grated provolone cheese",
        "2 teaspoons olive oil",
      ],
      steps: [
        "Preheat an oven to 450 degrees F (230 degrees C).",
        "Place chicken breasts between two sheets of heavy plastic (resealable freezer bags work well) on a solid, level surface. Firmly pound chicken with the smooth side of a meat mallet to a thickness of 1/2-inch.",
        "Season chicken thoroughly with salt and pepper. Using a sifter or strainer; sprinkle flour over chicken breasts, evenly coating both sides",
        "Beat eggs in a shallow bowl and set aside.",
        "Mix bread crumbs and 1/2 cup Parmesan cheese in a separate bowl, set aside.",
        "Dip a flour-coated chicken breast in beaten eggs. Transfer breast to the bread crumb mixture, pressing crumbs into both sides. Repeat for each breast. Let chicken rest for 10 to 15 minutes.",
        "Heat 1/2 inch olive oil in a large skillet on medium-high heat until it begins to shimmer. Cook chicken in the hot oil until golden, about 2 minutes per side. The chicken will finish cooking in the oven.",
        "Transfer chicken to a baking dish. Top each breast with 2 tablespoons tomato sauce. Layer each chicken breast with equal amounts of mozzarella cheese, fresh basil, and provolone cheese. Sprinkle remaining Parmesan over top and drizzle each with 1/2 teaspoon olive oil.",
        "Bake in the preheated oven until cheese is browned and bubbly and chicken breasts are no longer pink in the center, 15 to 20 minutes. An instant-read thermometer inserted into the center should read at least 165 degrees F (74 degrees C).",
      ],
    },
    reviews: [
      {
        user: "Bob",
        rating: 4,
        comment: "Nice!",
      },
      {
        user: "Jim",
        rating: 3,
        comment: "Cool!",
      },
      {
        user: "Nate",
        rating: 4.5,
        comment: "Sick!",
      },
    ],
    created: "August 29, 2023",
  },
  {
    id: 3,
    name: "Eggs Benedict",
    img: "/eggs-benedict.jpg",
    user: {
      name: "Chris"
    },
    information: {
      servings: 4,
      prepTime: 15,
      cookTime: 20,
      totalTime: 45,
      nuritionPerServing: {
        calories: 471,
        fat: 25,
        carbs: 25,
        protein: 42,
      },
      ingredients: [
        "4 skinless, boneless chicken breast halves",
        "salt and freshly ground black pepper to taste",
        "2 large eggs",
        "1 cup panko bread crumbs",
        "¾ cup grated Parmesan cheese, divided",
        "2 tablespoons all-purpose flour",
        "½ cup olive oil for frying",
        "½ cup prepared tomato sauce",
        "¼ cup fresh mozzarella, cut into small cubes",
        "¼ cup chopped fresh basil",
        "½ cup grated provolone cheese",
        "2 teaspoons olive oil",
      ],
      steps: [
        "Preheat an oven to 450 degrees F (230 degrees C).",
        "Place chicken breasts between two sheets of heavy plastic (resealable freezer bags work well) on a solid, level surface. Firmly pound chicken with the smooth side of a meat mallet to a thickness of 1/2-inch.",
        "Season chicken thoroughly with salt and pepper. Using a sifter or strainer; sprinkle flour over chicken breasts, evenly coating both sides",
        "Beat eggs in a shallow bowl and set aside.",
        "Mix bread crumbs and 1/2 cup Parmesan cheese in a separate bowl, set aside.",
        "Dip a flour-coated chicken breast in beaten eggs. Transfer breast to the bread crumb mixture, pressing crumbs into both sides. Repeat for each breast. Let chicken rest for 10 to 15 minutes.",
        "Heat 1/2 inch olive oil in a large skillet on medium-high heat until it begins to shimmer. Cook chicken in the hot oil until golden, about 2 minutes per side. The chicken will finish cooking in the oven.",
        "Transfer chicken to a baking dish. Top each breast with 2 tablespoons tomato sauce. Layer each chicken breast with equal amounts of mozzarella cheese, fresh basil, and provolone cheese. Sprinkle remaining Parmesan over top and drizzle each with 1/2 teaspoon olive oil.",
        "Bake in the preheated oven until cheese is browned and bubbly and chicken breasts are no longer pink in the center, 15 to 20 minutes. An instant-read thermometer inserted into the center should read at least 165 degrees F (74 degrees C).",
      ],
    },
    reviews: [
      {
        user: "Bob",
        rating: 4,
        comment: "Nice!",
      },
      {
        user: "Jim",
        rating: 3,
        comment: "Cool!",
      },
      {
        user: "Nate",
        rating: 4.5,
        comment: "Sick!",
      },
    ],
    created: "August 29, 2023",
  },
  {
    id: 4,
    name: "Eggs Benedict",
    img: "/eggs-benedict.jpg",
    user: {
      name: "Chris"
    },
    information: {
      servings: 4,
      prepTime: 15,
      cookTime: 20,
      totalTime: 45,
      nuritionPerServing: {
        calories: 471,
        fat: 25,
        carbs: 25,
        protein: 42,
      },
      ingredients: [
        "4 skinless, boneless chicken breast halves",
        "salt and freshly ground black pepper to taste",
        "2 large eggs",
        "1 cup panko bread crumbs",
        "¾ cup grated Parmesan cheese, divided",
        "2 tablespoons all-purpose flour",
        "½ cup olive oil for frying",
        "½ cup prepared tomato sauce",
        "¼ cup fresh mozzarella, cut into small cubes",
        "¼ cup chopped fresh basil",
        "½ cup grated provolone cheese",
        "2 teaspoons olive oil",
      ],
      steps: [
        "Preheat an oven to 450 degrees F (230 degrees C).",
        "Place chicken breasts between two sheets of heavy plastic (resealable freezer bags work well) on a solid, level surface. Firmly pound chicken with the smooth side of a meat mallet to a thickness of 1/2-inch.",
        "Season chicken thoroughly with salt and pepper. Using a sifter or strainer; sprinkle flour over chicken breasts, evenly coating both sides",
        "Beat eggs in a shallow bowl and set aside.",
        "Mix bread crumbs and 1/2 cup Parmesan cheese in a separate bowl, set aside.",
        "Dip a flour-coated chicken breast in beaten eggs. Transfer breast to the bread crumb mixture, pressing crumbs into both sides. Repeat for each breast. Let chicken rest for 10 to 15 minutes.",
        "Heat 1/2 inch olive oil in a large skillet on medium-high heat until it begins to shimmer. Cook chicken in the hot oil until golden, about 2 minutes per side. The chicken will finish cooking in the oven.",
        "Transfer chicken to a baking dish. Top each breast with 2 tablespoons tomato sauce. Layer each chicken breast with equal amounts of mozzarella cheese, fresh basil, and provolone cheese. Sprinkle remaining Parmesan over top and drizzle each with 1/2 teaspoon olive oil.",
        "Bake in the preheated oven until cheese is browned and bubbly and chicken breasts are no longer pink in the center, 15 to 20 minutes. An instant-read thermometer inserted into the center should read at least 165 degrees F (74 degrees C).",
      ],
    },
    reviews: [
      {
        user: "Bob",
        rating: 4,
        comment: "Nice!",
      },
      {
        user: "Jim",
        rating: 3,
        comment: "Cool!",
      },
      {
        user: "Nate",
        rating: 4.5,
        comment: "Sick!",
      },
    ],
    created: "August 29, 2023",
  },
  {
    id: 5,
    name: "Eggs Benedict",
    img: "/eggs-benedict.jpg",
    user: {
      name: "Chris"
    },
    information: {
      servings: 4,
      prepTime: 15,
      cookTime: 20,
      totalTime: 45,
      nuritionPerServing: {
        calories: 471,
        fat: 25,
        carbs: 25,
        protein: 42,
      },
      ingredients: [
        "4 skinless, boneless chicken breast halves",
        "salt and freshly ground black pepper to taste",
        "2 large eggs",
        "1 cup panko bread crumbs",
        "¾ cup grated Parmesan cheese, divided",
        "2 tablespoons all-purpose flour",
        "½ cup olive oil for frying",
        "½ cup prepared tomato sauce",
        "¼ cup fresh mozzarella, cut into small cubes",
        "¼ cup chopped fresh basil",
        "½ cup grated provolone cheese",
        "2 teaspoons olive oil",
      ],
      steps: [
        "Preheat an oven to 450 degrees F (230 degrees C).",
        "Place chicken breasts between two sheets of heavy plastic (resealable freezer bags work well) on a solid, level surface. Firmly pound chicken with the smooth side of a meat mallet to a thickness of 1/2-inch.",
        "Season chicken thoroughly with salt and pepper. Using a sifter or strainer; sprinkle flour over chicken breasts, evenly coating both sides",
        "Beat eggs in a shallow bowl and set aside.",
        "Mix bread crumbs and 1/2 cup Parmesan cheese in a separate bowl, set aside.",
        "Dip a flour-coated chicken breast in beaten eggs. Transfer breast to the bread crumb mixture, pressing crumbs into both sides. Repeat for each breast. Let chicken rest for 10 to 15 minutes.",
        "Heat 1/2 inch olive oil in a large skillet on medium-high heat until it begins to shimmer. Cook chicken in the hot oil until golden, about 2 minutes per side. The chicken will finish cooking in the oven.",
        "Transfer chicken to a baking dish. Top each breast with 2 tablespoons tomato sauce. Layer each chicken breast with equal amounts of mozzarella cheese, fresh basil, and provolone cheese. Sprinkle remaining Parmesan over top and drizzle each with 1/2 teaspoon olive oil.",
        "Bake in the preheated oven until cheese is browned and bubbly and chicken breasts are no longer pink in the center, 15 to 20 minutes. An instant-read thermometer inserted into the center should read at least 165 degrees F (74 degrees C).",
      ],
    },
    reviews: [
      {
        user: "Bob",
        rating: 4,
        comment: "Nice!",
      },
      {
        user: "Jim",
        rating: 3,
        comment: "Cool!",
      },
      {
        user: "Nate",
        rating: 4.5,
        comment: "Sick!",
      },
    ],
    created: "August 29, 2023",
  },
  {
    id: 6,
    name: "Eggs Benedict",
    img: "/eggs-benedict.jpg",
    user: {
      name: "Chris"
    },
    information: {
      servings: 4,
      prepTime: 15,
      cookTime: 20,
      totalTime: 45,
      nuritionPerServing: {
        calories: 471,
        fat: 25,
        carbs: 25,
        protein: 42,
      },
      ingredients: [
        "4 skinless, boneless chicken breast halves",
        "salt and freshly ground black pepper to taste",
        "2 large eggs",
        "1 cup panko bread crumbs",
        "¾ cup grated Parmesan cheese, divided",
        "2 tablespoons all-purpose flour",
        "½ cup olive oil for frying",
        "½ cup prepared tomato sauce",
        "¼ cup fresh mozzarella, cut into small cubes",
        "¼ cup chopped fresh basil",
        "½ cup grated provolone cheese",
        "2 teaspoons olive oil",
      ],
      steps: [
        "Preheat an oven to 450 degrees F (230 degrees C).",
        "Place chicken breasts between two sheets of heavy plastic (resealable freezer bags work well) on a solid, level surface. Firmly pound chicken with the smooth side of a meat mallet to a thickness of 1/2-inch.",
        "Season chicken thoroughly with salt and pepper. Using a sifter or strainer; sprinkle flour over chicken breasts, evenly coating both sides",
        "Beat eggs in a shallow bowl and set aside.",
        "Mix bread crumbs and 1/2 cup Parmesan cheese in a separate bowl, set aside.",
        "Dip a flour-coated chicken breast in beaten eggs. Transfer breast to the bread crumb mixture, pressing crumbs into both sides. Repeat for each breast. Let chicken rest for 10 to 15 minutes.",
        "Heat 1/2 inch olive oil in a large skillet on medium-high heat until it begins to shimmer. Cook chicken in the hot oil until golden, about 2 minutes per side. The chicken will finish cooking in the oven.",
        "Transfer chicken to a baking dish. Top each breast with 2 tablespoons tomato sauce. Layer each chicken breast with equal amounts of mozzarella cheese, fresh basil, and provolone cheese. Sprinkle remaining Parmesan over top and drizzle each with 1/2 teaspoon olive oil.",
        "Bake in the preheated oven until cheese is browned and bubbly and chicken breasts are no longer pink in the center, 15 to 20 minutes. An instant-read thermometer inserted into the center should read at least 165 degrees F (74 degrees C).",
      ],
    },
    reviews: [
      {
        user: "Bob",
        rating: 4,
        comment: "Nice!",
      },
      {
        user: "Jim",
        rating: 3,
        comment: "Cool!",
      },
      {
        user: "Nate",
        rating: 4.5,
        comment: "Sick!",
      },
    ],
    created: "August 29, 2023",
  },
];


export const singleRecipeData = {
  id: 1,
  name: "Eggs Benedict",
  img: "/eggs-benedict.jpg",
  user: {
    name: "Chris"
  },
  information: {
    servings: 4,
    prepTime: 15,
    cookTime: 20,
    totalTime: 45,
    nuritionPerServing: {
      calories: 471,
      fat: 25,
      carbs: 25,
      protein: 42,
    },
    description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut earum omnis obcaecati corrupti itaque nemo dolorum id doloremque quo nostrum?",
    ingredients: [
      "4 skinless, boneless chicken breast halves",
      "salt and freshly ground black pepper to taste",
      "2 large eggs",
      "1 cup panko bread crumbs",
      "¾ cup grated Parmesan cheese, divided",
      "2 tablespoons all-purpose flour",
      "½ cup olive oil for frying",
      "½ cup prepared tomato sauce",
      "¼ cup fresh mozzarella, cut into small cubes",
      "¼ cup chopped fresh basil",
      "½ cup grated provolone cheese",
      "2 teaspoons olive oil",
    ],
    steps: [
      "Preheat an oven to 450 degrees F (230 degrees C).",
      "Place chicken breasts between two sheets of heavy plastic (resealable freezer bags work well) on a solid, level surface. Firmly pound chicken with the smooth side of a meat mallet to a thickness of 1/2-inch.",
      "Season chicken thoroughly with salt and pepper. Using a sifter or strainer; sprinkle flour over chicken breasts, evenly coating both sides",
      "Beat eggs in a shallow bowl and set aside.",
      "Mix bread crumbs and 1/2 cup Parmesan cheese in a separate bowl, set aside.",
      "Dip a flour-coated chicken breast in beaten eggs. Transfer breast to the bread crumb mixture, pressing crumbs into both sides. Repeat for each breast. Let chicken rest for 10 to 15 minutes.",
      "Heat 1/2 inch olive oil in a large skillet on medium-high heat until it begins to shimmer. Cook chicken in the hot oil until golden, about 2 minutes per side. The chicken will finish cooking in the oven.",
      "Transfer chicken to a baking dish. Top each breast with 2 tablespoons tomato sauce. Layer each chicken breast with equal amounts of mozzarella cheese, fresh basil, and provolone cheese. Sprinkle remaining Parmesan over top and drizzle each with 1/2 teaspoon olive oil.",
      "Bake in the preheated oven until cheese is browned and bubbly and chicken breasts are no longer pink in the center, 15 to 20 minutes. An instant-read thermometer inserted into the center should read at least 165 degrees F (74 degrees C).",
    ],
  },
  reviews: [
    {
      user: "Bob",
      rating: 4,
      comment: "Nice!",
    },
    {
      user: "Jim",
      rating: 3,
      comment: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi, tenetur accusantium minus a deserunt ducimus repudiandae. Corporis ab excepturi necessitatibus quidem ad quia similique iusto.!",
    },
    {
      user: "Nate",
      rating: 4.5,
      comment: "Sick!",
    },
  ],
  created: "August 29, 2023",
}
